### ISSUE TITLE
表格样式丢失

### ISSUE THREAD

**Issue by mark-ck** [mark-ck/ablula-document-client#1]
RT

```
.ne-table{
  border-collapse: collapse;
}
.ne-table, th, td{
  border: 1px solid #000;
}
```

**Comment by eumenide** [comment]
语雀官方提供了样式文件：http://editor.yuque.com/ne-editor/lake-content-v1.css，也可以较好解决这个问题。

**Comment by mark-ck** [comment]
> 语雀官方提供了样式文件：http://editor.yuque.com/ne-editor/lake-content-v1.css ，也可以较好解决这个问题。

居然还有这个神器，已经在 @ablula/document-client@0.2.5 版本加上了~
