### ISSUE TITLE
使用过程中遇到的问题汇总

### ISSUE THREAD

**Issue by iJackyVon** [mark-ck/ablula-document-client#3]
1.左侧目录无法使用三级目录
2.右侧目录应该是树状结构
3.文档内容，各个段落间距比原文档间距变大了
4.内容的宽度随浏览器变宽了，最好能跟之前的一样，限制宽度，这样保证格式不乱
5.header隐藏之后，顶部的线无法去掉
6.表格丢样式

**Comment by mark-ck** [comment]
1、3、5、6 已解决，4 暂时 hold，2 我新建一个 issue 来跟进
